server:
  port: 2222
spring:
  application:
    name: zipkin-server
#RabbitMQ配置
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost
#服务注册中心地址配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/