server:
  port: 4444
spring:
  application:
    name: user-service
#RabbitMQ配置
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
#服务注册中心地址配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
